version: '3.9'
services:

  bookstore-server:
    build: 
      dockerfile: Dockerfile
      context: .
    image: bookstore:latest
    container_name: bookstore-server
    ports: 
      - 80:80
    restart: on-failure
    volumes:
      - api:/usr/src/app
    depends_on:
      - postgres          
    networks:
      - bookstore

  # DB working at 5432( in host/container ) & map to(expose to) at 5435.
  postgres:
    image: postgres:alpine
    container_name: bookstore-db
    environment:
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - 5435:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - bookstore

volumes:
  api:
  postgres:
  web-root:
    driver: local                  

# Networks to be created to facilitate communication between containers
networks:
  bookstore:
    driver: bridge
